version: "3.1"

services:
  device:
    build: .
    restart: on-failure
    environment:
      TZ: Europe/Berlin
    ports:
      - 127.0.0.1:80:3000
    depends_on:
      database:
    links:
      - database

  database:
    image: postgres:13.3
    restart: unless-stopped
    hostname: database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: mgr
      POSTGRES_PASSWORD: mgr
      POSTGRES_DB: mgr
  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db-data:
